# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    git_pull

    build_app(workspace: "Academus.xcworkspace", scheme: "Academus")
    increment_build_number(build_number: latest_testflight_build_number + 1, xcodeproj: "Academus.xcodeproj")
    upload_to_testflight(skip_waiting_for_build_processing: true)
    
    clean_build_artifacts
    commit_version_bump(message: "TestFlight Build #{latest_testflight_build_number + 1}" xcodeproj: "Academus.xcodeproj")
    add_git_tag
    push_to_git_remote
  end
end
